version: '3.8'

services:
  db:
    image: mysql:8.0.30
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=guardrails
      - MYSQL_PASSWORD=123!@#
      - MYSQL_ROOT_PASSWORD=thisjustneedstobeheredoesnotmatterwhatitis
      - MYSQL_USER=thuan
    networks:
      - guardrails-network
    volumes:
      - db:/var/lib/mysql
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: gr-api
    build: ./api
    # This is required because NextJS client will make requests from localhost
    ports:
      - 8080:8080
    networks:
      - guardrails-network
    env_file:
      - ./api/.env
    depends_on:
      - db
  dashboard:
    container_name: gr-dashboard
    build: ./dashboard
    depends_on:
      - api
    ports:
      - 3000:3000
    networks:
      - guardrails-network
    env_file:
      - ./dashboard/.env
networks:
  guardrails-network:
    driver: bridge
volumes:
  db:
    driver: local